# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 110048e706c37dff6a32940f84f8bec8830482a33c1a8a7043430197f6c2b515e6a0c6184071b64223e0e8ee5be6d075e59d8ab21d1faef477f840b6ef1badeb

test:
  secret_key_base: 0c638fca79ba727de88c126284cf76ad5b15b3b67b66af5fb5912637714c3c37998667c45bb303a7b968af49d4a20923797fea15348eb850a01a46bb9a35b288

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
