# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)




osone = OfficeSought.create(category: 'Mayor, City of Houston')
ostwo = OfficeSought.create(category: 'City Council-District A')
osthree = OfficeSought.create(category: 'City Council- District B')
osfour = OfficeSought.create(category: 'City Council-District C')
osfive = OfficeSought.create(category: 'City Council- District D')
ossix = OfficeSought.create(category: 'City Council-District E')
osseven = OfficeSought.create(category: 'City Council- District F')
oseigth = OfficeSought.create(category: 'City Council-District G')
osnine = OfficeSought.create(category: 'City Council- District H')
osten = OfficeSought.create(category: 'City Council-District I')
oseleven = OfficeSought.create(category: 'City Council- District J')
ostwelve=  OfficeSought.create(category: 'City Council-District K')
osthirteen = OfficeSought.create(category: 'City Council, At Large Position 1')
osfourteen = OfficeSought.create(category: 'City Council, At Large Position 2')
osfifteen = OfficeSought.create(category: 'City Council, At Large Position 3')
ossixteen = OfficeSought.create(category: 'City Council, At Large Position 4')
osseventeen = OfficeSought.create(category: 'City Council, At Large Position 5')
oseighteen = OfficeSought.create(category: 'Controller')
osnineteen = OfficeSought.create(category: 'Harris County School Trustee Position 6, PCT 1')
ostwenty = OfficeSought.create(category: 'Texas State Board of Education, District 4')
ostwentyone = OfficeSought.create(category: 'Trustee-Houston Community College District IV')
ostwentytwo = OfficeSought.create(category: 'None')

ohone = OfficeHeld.create(category: 'Mayor, City of Houston')
ohtwo = OfficeHeld.create(category: 'City Council-District A')
ohthree = OfficeHeld.create(category: 'City Council- District B')
ohfour = OfficeHeld.create(category: 'City Council-District C')
ohfive = OfficeHeld.create(category: 'City Council- District D')
ohsix = OfficeHeld.create(category: 'City Council-District E')
ohseven = OfficeHeld.create(category: 'City Council- District F')
oheight = OfficeHeld.create(category: 'City Council-District G')
ohnine = OfficeHeld.create(category: 'City Council- District H')
ohten = OfficeHeld.create(category: 'City Council-District I')
oheleven = OfficeHeld.create(category: 'City Council- District J')
ohtwelve = OfficeHeld.create(category: 'City Council-District K')
ohthirteen = OfficeHeld.create(category: 'City Council, At Large Position 1')
ohfourteen = OfficeHeld.create(category: 'City Council, At Large Position 2')
ohfifteen = OfficeHeld.create(category: 'City Council, At Large Position 3')
ohsixteen = OfficeHeld.create(category: 'City Council, At Large Position 4')
ohseventeen = OfficeHeld.create(category: 'City Council, At Large Position 5')
oheighteen = OfficeHeld.create(category: 'Controller')
ohnineteen = OfficeHeld.create(category: 'Harris County School Trustee Position 6, PCT 1')
ohtwenty = OfficeHeld.create(category: 'Texas State Board of Education, District 4')
ohtwentyone = OfficeHeld.create(category: 'Trustee-Houston Community College District IV')
ohtwentytwo = OfficeHeld.create(category: 'None')

general = CommitteeType.create(committeetype: 'General')
specific = CommitteeType.create(committeetype: 'Specific')

hon = Prefix.create(prefix: 'Hon')
mr = Prefix.create(prefix: 'Mr.')
ms = Prefix.create(prefix: 'Ms.')
miss = Prefix.create(prefix: 'Miss.')
mrs = Prefix.create(prefix: 'Mrs.')
dr = Prefix.create(prefix: 'Dr.')
gov = Prefix.create(prefix: 'Gov.')
rep = Prefix.create(prefix: 'Rep')
sen = Prefix.create(prefix: 'Sen.')
prof = Prefix.create(prefix: 'Prof.')

prim = ElectionType.create(ectype: 'Primary')
general = ElectionType.create(ectype: 'General')
runoff = ElectionType.create(ectype: 'Runoff')
special = ElectionType.create(ectype: 'Special')
other = ElectionType.create(ectype: 'Other')

rpone = ReportType.create(rtype: 'COH')
rptwo = ReportType.create(rtype: 'SPAC')

econe = ExpendCategory.create(category: 'Accounting')
ectwo = ExpendCategory.create(category: 'Banking')
ecthree = ExpendCategory.create(category: 'Advertising Expense')
ecfour = ExpendCategory.create(category: 'Consulting Expense')
ecfive = ExpendCategory.create(category: 'Contributions Made By Candidate/OfficeHolder')
ecsix = ExpendCategory.create(category: 'Contributions Made By Politcal Committee')
ecseven = ExpendCategory.create(category: 'Donations Made By Candidate/OfficeHolder')
eceight = ExpendCategory.create(category: 'Donations Made By Politcal Committee')
ecnine = ExpendCategory.create(category: 'Event Expense')
ecten = ExpendCategory.create(category: 'Fees')
eceleven = ExpendCategory.create(category: 'Food and Beverage Expense')
ectwelve = ExpendCategory.create(category: 'Gifts and Awards Expense')
ecthirteen = ExpendCategory.create(category: 'Memorials Expense')
ecfourteen = ExpendCategory.create(category: 'Legal Services')
ecfifteen = ExpendCategory.create(category: 'Loan Repayment and Reimbursement Office Rental Expense')
ecsixteen = ExpendCategory.create(category: 'Polling Expense')
ecseventeen = ExpendCategory.create(category: 'Printing Expense')
eceighteen = ExpendCategory.create(category: 'Salaries')
ecnineteen = ExpendCategory.create(category: 'Wages')
ectwenty = ExpendCategory.create(category: 'Contract Labor')
ectwentyone = ExpendCategory.create(category: 'Solicitation and Fundraising Expense')
ectwentytwo = ExpendCategory.create(category: 'Transportation Equipment & Related Expense')
ectwentythree = ExpendCategory.create(category: 'Travel in District')
ectwentyfour = ExpendCategory.create(category: 'Travel Out District')
ectwentyfive = ExpendCategory.create(category: 'Other Expenditures')

political = ExpendType.create(extype: 'Political')
nonpolitical = ExpendType.create(extype: 'Non-Political')


co = FilerType.create(ftype: 'Candidate/Officeholder')
pc = FilerType.create(ftype: 'Political Committee')
